# Generated by Django 3.2.7 on 2021-09-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.neighborhood'),
        ),
    ]
