# Generated by Django 3.2.7 on 2021-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210929_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='admin_contact',
            new_name='healthcare_toll',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_toll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
